# Generated by Django 4.2.8 on 2024-01-06 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='picture',
            field=models.ImageField(blank=True, default='default-poster.png', null=True, upload_to='alum'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='poster',
            field=models.ImageField(blank=True, default='default-poster.png', null=True, upload_to='updates'),
        ),
        migrations.AlterField(
            model_name='fest',
            name='poster',
            field=models.ImageField(blank=True, default='default-poster.png', null=True, upload_to='fests'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='poster',
            field=models.ImageField(blank=True, default='default-poster.png', null=True, upload_to='seminars'),
        ),
    ]
