# Generated by Django 4.2.7 on 2024-01-08 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alumni_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='info',
            new_name='information',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='fest',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='studentinitiative',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='desc',
            new_name='description',
        ),
    ]
