# Generated by Django 4.2.8 on 2024-01-14 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('main', '0005_studentinitiative_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('scope', models.CharField(default='read_only', max_length=20)),
            ],
            bases=('authtoken.token',),
        ),
    ]
