# Generated by Django 5.0.4 on 2024-04-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_competition_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='seminar',
            name='link',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
