# Generated by Django 5.0.4 on 2024-04-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_seminar_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='linkedin_link',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
