# Generated by Django 4.2.8 on 2024-06-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_competition_created_by_fest_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='notice_img',
            field=models.FileField(blank=True, default='default-poster.png', null=True, upload_to='notices'),
        ),
    ]
