# Generated by Django 4.2.8 on 2026-02-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_fcmdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='linkedin_link',
            field=models.URLField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
