# Generated by Django 4.2.8 on 2026-02-07 16:32

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_alumni_department_alter_alumni_linkedin_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[main.models.validate_description_length]),
        ),
        migrations.AddField(
            model_name='seminar',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[main.models.validate_description_length]),
        ),
        migrations.AlterField(
            model_name='competition',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[main.models.validate_description_length]),
        ),
        migrations.AlterField(
            model_name='fest',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[main.models.validate_description_length]),
        ),
        migrations.AlterField(
            model_name='studentinitiative',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[main.models.validate_description_length]),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[main.models.validate_description_length]),
        ),
    ]
